name: daily_care_ui
description: DailyCare UI

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  circular_bottom_navigation: ^2.0.0
  google_fonts: ^2.3.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/fonts/

  fonts:
    - family: DailyCareIcons
      fonts:
        - asset: assets/fonts/DailyCareIcons.ttf


